### ISSUE TITLE
Failed to connect to opendev gerrit server.

### ISSUE THREAD

**Issue by rahmanih** [change-metrics/monocle#1121]
Hi,
I'm trying to run monocle using the sample config file provided but nothing is displayed on the dashboard.![image](https://github.com/change-metrics/monocle/assets/3645021/2ce636f8-b704-4b42-bd0b-c66d345f334f)

lookig at the logs I can see the following errors
````
crawler_1  | 2024-05-27 11:02:00 INFO    Macroscope.Main:88: Starting monitoring service {"port":9001}
crawler_1  | 2024-05-27 11:02:00 INFO    Macroscope.Main:115: Starting to fetch streams
crawler_1  | 2024-05-27 11:02:00 INFO    Macroscope.Main:168: Starting crawlers {"crawlers":["https://review.opendev.org for opendev_crawler"]}
crawler_1  | 2024-05-27 11:02:00 INFO    Macroscope.Main:182: Group starting {"group":"https://review.opendev.org for opendev_crawler"}
crawler_1  | 2024-05-27 11:02:00 INFO    Macroscope.Main:321: Starting crawler {"index":"opendev","crawler":"opendev_crawler"}
crawler_1  | 2024-05-27 11:02:00 INFO    Macroscope.Worker:183: Looking for oldest entity {"index":"opendev","crawler":"opendev_crawler","stream":"Changes","offset":0}
crawler_1  | 2024-05-27 11:02:00 WARNING Monocle.Effects:564: network error {"index":"opendev","crawler":"opendev_crawler","stream":"Changes","count":0,"limit":7,"loc":"api:8080/api/2/crawler/get_commit_info","failed":"ConnectionFailure Network.Socket.connect: <socket: 24>: does not exist (Connection refused)"}
crawler_1  | 2024-05-27 11:02:00 WARNING Monocle.Effects:564: network error {"index":"opendev","crawler":"opendev_crawler","stream":"Changes","count":1,"limit":7,"loc":"api:8080/api/2/crawler/get_commit_info","failed":"ConnectionFailure Network.Socket.connect: <socket: 24>: does not exist (Connection refused)"}
crawler_1  | 2024-05-27 11:02:02 WARNING Monocle.Effects:564: network error {"index":"opendev","crawler":"opendev_crawler","stream":"Changes","count":2,"limit":7,"loc":"api:8080/api/2/crawler/get_commit_info","failed":"ConnectionFailure Network.Socket.connect: <socket: 24>: does not exist (Connection refused)"}
crawler_1  | 2024-05-27 11:02:04 WARNING Monocle.Effects:564: network error {"index":"opendev","crawler":"opendev_crawler","stream":"Changes","count":3,"limit":7,"loc":"api:8080/api/2/crawler/get_commit_info","failed":"ConnectionFailure Network.Socket.connect: <socket: 24>: does not exist (Connection refused)"}
crawler_1  | 2024-05-27 11:02:08 WARNING Monocle.Effects:564: network error {"index":"opendev","crawler":"opendev_crawler","stream":"Changes","count":4,"limit":7,"loc":"api:8080/api/2/crawler/get_commit_info","failed":"ConnectionFailure Network.Socket.connect: <socket: 24>: does not exist (Connection refused)"}
crawler_1  | 2024-05-27 11:02:16 WARNING Monocle.Effects:564: network error {"index":"opendev","crawler":"opendev_crawler","stream":"Changes","count":5,"limit":7,"loc":"api:8080/api/2/crawler/get_commit_info","failed":"ConnectionFailure Network.Socket.connect: <socket: 24>: does not exist (Connection refused)"}
crawler_1  | 2024-05-27 11:02:32 WARNING Monocle.Effects:564: network error {"index":"opendev","crawler":"opendev_crawler","stream":"Changes","count":6,"limit":7,"loc":"api:8080/api/2/crawler/get_commit_info","failed":"ConnectionFailure Network.Socket.connect: <socket: 24>: does not exist (Connection refused)"}
crawler_1  | 2024-05-27 11:03:04 INFO    Macroscope.Worker:199: Processing {"index":"opendev","crawler":"opendev_crawler","stream":"Changes","entity":{"contents":"openstack/nova","tag":"Project"},"age":"2024-01-01T00:00:00Z"}
````

````
lastic_1  | "stacktrace": ["java.net.UnknownHostException: geoip.elastic.co",
elastic_1  | "at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]",
elastic_1  | "at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]",
elastic_1  | "at java.net.Socket.connect(Socket.java:751) ~[?:?]",
elastic_1  | "at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]",
elastic_1  | "at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]",
elastic_1  | "at sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]",
elastic_1  | "at sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]",
elastic_1  | "at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]",
elastic_1  | "at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377) ~[?:?]",
elastic_1  | "at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]",
elastic_1  | "at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237) ~[?:?]",
elastic_1  | "at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123) ~[?:?]",
elastic_1  | "at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]",
elastic_1  | "at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675) ~[?:?]",
elastic_1  | "at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?]",
elastic_1  | "at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531) ~[?:?]",
elastic_1  | "at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307) ~[?:?]",
elastic_1  | "at org.elasticsearch.ingest.geoip.HttpClient.lambda$get$0(HttpClient.java:55) ~[ingest-geoip-7.17.16.jar:7.17.16]",
elastic_1  | "at java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]",
elastic_1  | "at org.elasticsearch.ingest.geoip.HttpClient.doPrivileged(HttpClient.java:97) ~[ingest-geoip-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.ingest.geoip.HttpClient.get(HttpClient.java:49) ~[ingest-geoip-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.ingest.geoip.HttpClient.getBytes(HttpClient.java:40) ~[ingest-geoip-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.ingest.geoip.GeoIpDownloader.fetchDatabasesOverview(GeoIpDownloader.java:159) ~[ingest-geoip-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:147) ~[ingest-geoip-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:284) [ingest-geoip-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:100) [ingest-geoip-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:46) [ingest-geoip-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42) [elasticsearch-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.16.jar:7.17.16]",
elastic_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.16.jar:7.17.16]",
elastic_1  | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]",
elastic_1  | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]",
elastic_1  | "at java.lang.Thread.run(Thread.java:1583) [?:?]"] }
````

to notice that I'm working behind an network **http proxy.**, and I'm not sure how to configure it correctly.

any idea please?

regards
Haithem.

**Comment by TristanCacqueray** [comment]
Hello, have you set the HTTPS_PROXY environment variable?

**Comment by TristanCacqueray** [comment]
Yes that should work.

**Comment by rahmanih** [comment]
> Ok, but that sounds like a regression from #1029. 

https://github.com/change-metrics/monocle/blob/d2232bffee1a381c991854dea7abc6784926137c/nix/default.nix#L125
IIRC, this change is for 'nix', how  is  this deployed for docker?

>Have you set the HTTPS_PROXY environment variable in the docker-compose.yml file (e.g. in the `.secret` and the `elastic.environment` sections)?

Done as below:
````
     env_file: ".secrets"
     environment:
+      HTTPS_PROXY: "http://<login>:<password>@<proxy_server>:<port>"
       MONOCLE_CONFIG: /etc/monocle/config.yaml
       MONOCLE_PUBLIC_URL: http://api:8080
     healthcheck:
@@ -39,6 +41,7 @@ services:
       - "./etc:/etc/monocle:z"
   elastic:
     environment:
+      HTTPS_PROXY: "http://<login>:<password>@<proxy_server>:<port>"
       ES_JAVA_OPTS: "-Xms${COMPOSE_ES_XMS:-512m} -Xmx${COMPOSE_ES_XMX:-512m}"
       discovery.type: single-node
````

**Comment by rahmanih** [comment]
> > Ok, but that sounds like a regression from #1029.
> 
> https://github.com/change-metrics/monocle/blob/d2232bffee1a381c991854dea7abc6784926137c/nix/default.nix#L125
> 
> 
> IIRC, this change is for 'nix', how is this deployed for docker?
> > Have you set the HTTPS_PROXY environment variable in the docker-compose.yml file (e.g. in the `.secret` and the `elastic.environment` sections)?
> 
> Done as below:
> 
> ```
>      env_file: ".secrets"
>      environment:
> +      HTTPS_PROXY: "http://<login>:<password>@<proxy_server>:<port>"
>        MONOCLE_CONFIG: /etc/monocle/config.yaml
>        MONOCLE_PUBLIC_URL: http://api:8080
>      healthcheck:
> @@ -39,6 +41,7 @@ services:
>        - "./etc:/etc/monocle:z"
>    elastic:
>      environment:
> +      HTTPS_PROXY: "http://<login>:<password>@<proxy_server>:<port>"
>        ES_JAVA_OPTS: "-Xms${COMPOSE_ES_XMS:-512m} -Xmx${COMPOSE_ES_XMX:-512m}"
>        discovery.type: single-node
> ```

I succeeded to run using **NixOS** , but there isn't any data displayed on the browser.
![image_2024-06-10_112530394](https://github.com/change-metrics/monocle/assets/3645021/9498b527-1961-44d9-8d8a-dcbac13366de)
 and the the following error log is shown:

````
org.elasticsearch.common.compress.NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes
	at org.elasticsearch.common.compress.CompressorFactory.compressor(CompressorFactory.java:42) ~[elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:123) ~[elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.rest.action.admin.indices.RestPutMappingAction.prepareRequest(RestPutMappingAction.java:80) ~[elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:86) ~[elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.xpack.security.rest.SecurityRestFilter.handleRequest(SecurityRestFilter.java:99) ~[?:?]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:340) [elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:405) [elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:252) [elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:384) [elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:478) [elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:358) [elasticsearch-7.17.16.jar:7.17.16]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:35) [transport-netty4-client-7.17.16.jar:7.17.16]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:19) [transport-netty4-client-7.17.16.jar:7.17.16]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:48) [transport-netty4-client-7.17.16.jar:7.17.16]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at org.elasticsearch.http.netty4.Netty4HttpHeaderValidator.forwardData(Netty4HttpHeaderValidator.java:194) [transport-netty4-client-7.17.16.jar:7.17.16]
	at org.elasticsearch.http.netty4.Netty4HttpHeaderValidator.forwardFullRequest(Netty4HttpHeaderValidator.java:137) [transport-netty4-client-7.17.16.jar:7.17.16]
	at org.elasticsearch.http.netty4.Netty4HttpHeaderValidator.lambda$requestStart$1(Netty4HttpHeaderValidator.java:120) [transport-netty4-client-7.17.16.jar:7.17.16]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [netty-common-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) [netty-common-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) [netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.94.Final.jar:4.1.94.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]

````
any help please?
