### ISSUE TITLE
Api and crawler containers are crashing

### ISSUE THREAD

**Issue by dmarcoux** [change-metrics/monocle#249]
Hey,

I'm trying to use Monocle and the api and crawler containers are both crashing. Here are the logs from the containers:

```bash
$ docker-compose logs api
Attaching to monocle_api_1
api_1      | internal/modules/cjs/loader.js:969
api_1      |   throw err;
api_1      |   ^
api_1      | Error: Cannot find module '/app/uwsgi'
api_1      |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
api_1      |     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
api_1      |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
api_1      |     at internal/main/run_main_module.js:17:47 {
api_1      |   code: 'MODULE_NOT_FOUND',
api_1      |   requireStack: []
api_1      | }
```

```bash
$ docker-compose logs crawler
Attaching to monocle_crawler_1
crawler_1  | internal/modules/cjs/loader.js:969
crawler_1  |   throw err;
crawler_1  |   ^
crawler_1  | Error: Cannot find module '/app/monocle'
crawler_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
crawler_1  |     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
crawler_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
crawler_1  |     at internal/main/run_main_module.js:17:47 {
crawler_1  |   code: 'MODULE_NOT_FOUND',
crawler_1  |   requireStack: []
crawler_1  | }
```

I followed the instructions from the README.

**Comment by morucci** [comment]
Hi,

We recently switched to a github action to publish the container images and it seems to be broken. I'm able to reproduce the issue.

Until we find the fix, you could still build the container images:

- rm docker-compose.yml
- ln -s docker-compose.yml.dev docker-compose.yml
- docker-compose build
- docker-compose up -d

**Comment by dmarcoux** [comment]
It solved the issue. Thank you for the quick reply.
